# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u-Eloh-W5d89s4AwSDJmCgSQpEQ7-jJc
"""

import setuptools
from pathlib import Path
#from setuptools import setup
setuptools.setup(name='gym_stopping',
      version='0.0.0',
      description="A OpenAI Gym Env for continuous control",
      long_description=Path("README.md").read_text(),
      long_description_content_type="text/markdown",
                 author="Claudia Viaro",
                 license="MIT",
      packages=setuptools.find_packages(include="gym_stopping*"),
      install_requires=['gym']  # And any other dependencies needed
)